### ISSUE TITLE
CodeCarbon much too verbose. can verbosity be changed?

### ISSUE THREAD

**Issue by MoritzLaurer** [mlco2/codecarbon#298] opened 2022-04-18 18:07 UTC
* CodeCarbon version: 2.0.0
* Python version: 3.7
* Operating System: Linux (google colab). (testing with a CPU, not GPU)

### Description

I've integrated code carbon in a google colab with several pytorch training loops. I start it at the very beginning and stop at the very end as indicated in the documentation. When I run my script, it outputs updates at way too frequent intervals, see extract below. can I reduce the verbosity somehow? 

```
from codecarbon import OfflineEmissionsTracker
tracker = OfflineEmissionsTracker(country_iso_code="NLD", output_dir=TRAINING_DIRECTORY,  project_name=f"{DATASET_NAME}-{MODEL_NAME.split('/')[-1]}")
tracker.start()

# ... some code looping over several pytorch training loops for hyperparameter tuning

# extract of output in my notebook cell: 
[codecarbon INFO @ 17:56:19] Energy consumed for RAM : 0.000119 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:19] Energy consumed for all CPUs : 0.001063 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:19] 0.001182 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:27] Energy consumed for RAM : 0.006738 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:27] Energy consumed for all CPUs : 0.060201 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:27] 0.066939 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:31] Energy consumed for RAM : 0.007332 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:31] Energy consumed for all CPUs : 0.065512 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:31] 0.072844 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:33] Energy consumed for RAM : 0.000020 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:33] Energy consumed for all CPUs : 0.000177 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:33] 0.000197 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:34] Energy consumed for RAM : 0.000139 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:34] Energy consumed for all CPUs : 0.001240 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:34] 0.001378 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:42] Energy consumed for RAM : 0.006757 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:42] Energy consumed for all CPUs : 0.060378 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:42] 0.067135 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:46] Energy consumed for RAM : 0.007352 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:46] Energy consumed for all CPUs : 0.065689 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:46] 0.073041 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:48] Energy consumed for RAM : 0.000040 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:48] Energy consumed for all CPUs : 0.000354 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:48] 0.000394 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:49] Energy consumed for RAM : 0.000159 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:49] Energy consumed for all CPUs : 0.001417 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:49] 0.001575 kWh of electricity used since the begining.
[codecarbon INFO @ 17:56:57] Energy consumed for RAM : 0.006777 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 17:56:57] Energy consumed for all CPUs : 0.060555 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 17:56:57] 0.067332 kWh of electricity used since the begining.
```

Edit: And a second question: I don't fully understand why the numbers at the different iterations of "XXX kWh of electricity used since the beginning" don't sum up. My intuition would have been that these numbers sum up as the code progresses, but they don't. Not sure if that indicates an issue?

**Comment by benoit-cty** [comment] 2022-04-19 16:56
Hello,
You could change the verbosity with `log_level='error'`
```
        :param log_level: Global codecarbon log level. Accepts one of:
                            {"debug", "info", "warning", "error", "critical"}.
                          Defaults to "info".
```

You are right, `_total_energy` look like to have a bug, thanks for reporting this !

**Comment by MoritzLaurer** [comment] 2022-04-19 17:26
ok, thank you!

**Comment by benoit-cty** [comment] 2022-04-19 19:47
Yes,
CodeCarbon is developed with flexibility in mind. This means you don't have to keep passing the same arguments over and over to `EmissionTracker` objects in your scripts. Any and all arguments can be set from configuration files or environment variables. CodeCarbon will look sequentially for arguments in:

- `~/.codecarbon.config` (global user config)
- `./.codecarbon.config` (local directory config)
- `CODECARBON_ARG` (environment variables)
- `EmissionsTracker(arg=value)`

Config files are INI text files which should look like:

```ini
[codecarbon]
log_level = ERROR
```


For `kWh of electricity used since the beginning.` I made a test and it works for me.
But the interval between too log is too short, default value is 15 seconds.
Did you instantiate multiple EmissionsTracker ? 
Could you send the beginning of the log to see the tracking mode ?

**Comment by MoritzLaurer** [comment] 2022-04-20 07:27
I'm pretty sure that I'm only instantiating the EmissionsTracker once. 

Here is the initialisation: 
```
from codecarbon import OfflineEmissionsTracker
tracker = OfflineEmissionsTracker(country_iso_code="NLD", output_dir=TRAINING_DIRECTORY,  project_name="test")
tracker.start()

# output in notebook cell: 
[codecarbon INFO @ 20:33:15] offline tracker init
[codecarbon INFO @ 20:33:15] [setup] RAM Tracking...
[codecarbon INFO @ 20:33:15] [setup] GPU Tracking...
[codecarbon INFO @ 20:33:15] Tracking Nvidia GPU via pynvml
[codecarbon INFO @ 20:33:15] [setup] CPU Tracking...
[codecarbon WARNING @ 20:33:15] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon WARNING @ 20:33:17] We saw that you have a Intel(R) Xeon(R) CPU @ 2.30GHz but we don't know it. Please contact us.
[codecarbon INFO @ 20:33:17] CPU Model on constant consumption mode: Intel(R) Xeon(R) CPU @ 2.30GHz
[codecarbon INFO @ 20:33:17] >>> Tracker's metadata:
[codecarbon INFO @ 20:33:17]   Platform system: Linux-5.4.144+-x86_64-with-Ubuntu-18.04-bionic
[codecarbon INFO @ 20:33:17]   Python version: 3.7.13
[codecarbon INFO @ 20:33:17]   Available RAM : 12.687 GB
[codecarbon INFO @ 20:33:17]   CPU count: 2
[codecarbon INFO @ 20:33:17]   CPU model: Intel(R) Xeon(R) CPU @ 2.30GHz
[codecarbon INFO @ 20:33:17]   GPU count: 1
[codecarbon INFO @ 20:33:17]   GPU model: 1 x Tesla P100-PCIE-16GB
```

##

**Comment by MoritzLaurer** [comment] 2022-04-20 07:32
It seems like it outputs co2 consumption updates at certain, frequent intervals (15 sec), whether the cells consumes much energy or not. for example, under a totally normal cell like this: 

```
### import local functions
from google.colab import drive
import sys, os
drive.mount('/content/drive', force_remount=False)
#drive.flush_and_unmount()
print(os.getcwd())
os.chdir("/content/drive/My Drive/Colab Notebooks/")
print(os.getcwd())

sys.path.append("/content/drive/My Drive/Colab Notebooks/")

import few_shot_func
import importlib  # in case of manual updates in .py file
importlib.reload(few_shot_func)

from few_shot_func import random_sample_fill, format_nli_testset, format_nli_trainset  # custom_train_test_split, custom_train_test_split_sent_overlapp
from few_shot_func import load_model_tokenizer, tokenize_datasets, set_train_args, create_trainer
from few_shot_func import compute_metrics_standard, compute_metrics_nli_binary, compute_metrics_classical_ml, clean_memory, aug_back_translation

from sklearn.model_selection import train_test_split
np.random.seed(SEED_GLOBAL)

```

I get the output: 
```
[codecarbon INFO @ 07:27:02] Energy consumed for RAM : 0.000020 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 07:27:02] Energy consumed for all CPUs : 0.000177 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 07:27:02] 0.000197 kWh of electricity used since the begining.
```

Can the frequency be reduced to updates very 5 minutes or so?

**Comment by benoit-cty** [comment] 2022-04-20 10:09
You are using the package the right way, you could reduce the interval with `measure_power_secs=300`

What surprise me is that you have a `Tesla P100-PCIE-16GB` but it is not monitored.

**Comment by MoritzLaurer** [comment] 2022-04-21 07:50
thanks for pointing out the measure_power_secs argument!

Regarding the GPU monitoring: I've been switching around between CPU and GPU for my tests. so for some of the outputs above, it was only running on a CPU, so that's probably not an issue on your end. 

(What still seems weird is that the kwh don't seem to sum up in the printed output)

**Comment by MoritzLaurer** [comment] 2022-04-21 11:18
Update: I now use this initialisation: (running on a CPU in google colab)
```
from codecarbon import OfflineEmissionsTracker
tracker = OfflineEmissionsTracker(country_iso_code="NLD", output_dir=TRAINING_DIRECTORY,  log_level='warning', measure_power_secs=300, project_name=f"asdf")
tracker.start()
```

and I still get very frequent output, although measure_power_secs=300 and log_level='warning':

```
[codecarbon INFO @ 11:13:17] Energy consumed for RAM : 0.000020 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:13:17] Energy consumed for all CPUs : 0.000177 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:13:17] 0.000197 kWh of electricity used since the begining.
[codecarbon INFO @ 11:13:32] Energy consumed for RAM : 0.000040 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:13:32] Energy consumed for all CPUs : 0.000354 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:13:32] 0.000394 kWh of electricity used since the begining.
[codecarbon INFO @ 11:13:47] Energy consumed for RAM : 0.000059 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:13:47] Energy consumed for all CPUs : 0.000532 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:13:47] 0.000591 kWh of electricity used since the begining.
[codecarbon INFO @ 11:14:02] Energy consumed for RAM : 0.000079 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:14:02] Energy consumed for all CPUs : 0.000709 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:14:02] 0.000788 kWh of electricity used since the begining.
[codecarbon INFO @ 11:14:17] Energy consumed for RAM : 0.000099 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:14:17] Energy consumed for all CPUs : 0.000886 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:14:17] 0.000985 kWh of electricity used since the begining.
[codecarbon INFO @ 11:14:32] Energy consumed for RAM : 0.000119 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:14:32] Energy consumed for all CPUs : 0.001063 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:14:32] 0.001181 kWh of electricity used since the begining.
[codecarbon INFO @ 11:14:47] Energy consumed for RAM : 0.000139 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:14:47] Energy consumed for all CPUs : 0.001240 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:14:47] 0.001378 kWh of electricity used since the begining.
[codecarbon INFO @ 11:15:02] Energy consumed for RAM : 0.000158 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:15:02] Energy consumed for all CPUs : 0.001417 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:15:02] 0.001575 kWh of electricity used since the begining.
[codecarbon INFO @ 11:15:17] Energy consumed for RAM : 0.000178 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:15:17] Energy consumed for all CPUs : 0.001594 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:15:17] 0.001772 kWh of electricity used since the begining.
[codecarbon INFO @ 11:15:32] Energy consumed for RAM : 0.000198 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:15:32] Energy consumed for all CPUs : 0.001771 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:15:32] 0.001969 kWh of electricity used since the begining.
[codecarbon INFO @ 11:15:47] Energy consumed for RAM : 0.000218 kWh. RAM Power : 4.757494926452637 W
[codecarbon INFO @ 11:15:47] Energy consumed for all CPUs : 0.001948 kWh. All CPUs Power : 42.5 W
[codecarbon INFO @ 11:15:47] 0.002166 kWh of electricity used since the begining.

```

**Comment by benoit-cty** [comment] 2022-05-24 21:18
Hello,
I'm not able to reproduce, I have the expected behavior. Could you execute the file https://github.com/mlco2/codecarbon/pull/311/files#diff-c0d24196d74b1afe05099f8f81055c5744ba1aeb353c2949bdaea3c219f5f0e9 in your environment ?
It will log debug to a codecarbon.log file and only display Warning and Error.

**Comment by KasperGroesLudvigsen** [comment] 2022-09-03 23:23
@benoit-cty does the `measure_power_secs` argument affect the actual measurements or only how frequently print outs are made?

**Comment by benoit-cty** [comment] 2022-09-04 08:33
@KasperGroesLudvigsen It affects the measures because it is the interval between two measures.

With rapl it could be very high because we read an energy counter so you always get accurate results.

For GPU we read instant power, then Compute energy over time. If you have many variations in power usage it's not perfect.

**Comment by benoit-cty** [comment] 2022-10-25 19:14
Can we close the issue, do you still have the problem ?

**Comment by MoritzLaurer** [comment] 2022-10-26 08:10
I haven't tried it in a while, I think you can close, thanks for your responses

**Closed** 2022-10-26 20:28 UTC
Labels: bug, good first issue
