### ISSUE TITLE
GPU power is 0

### ISSUE THREAD

**Issue by giuspillo** [mlco2/codecarbon#393] opened 2023-04-17 13:28 UTC
Dear authors,

I guess I'm having an issue, the GPU is not being tracked correctly.
I'm executing a recommendation algorithm using the GPU (as you can see from the output, the field "device" has value "cuda"),
but I guess CodeCarbon is not tracking it since the final power is 0.

I will attach the full output on a separate file, here I will highlight the most relevant lines.

```
[codecarbon INFO @ 15:08:58] [setup] RAM Tracking...
[codecarbon INFO @ 15:08:58] [setup] GPU Tracking...
[codecarbon INFO @ 15:08:58] Tracking Nvidia GPU via pynvml
[codecarbon INFO @ 15:08:58] [setup] CPU Tracking...
[codecarbon INFO @ 15:08:58] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 15:08:59] >>> Tracker's metadata:
[codecarbon INFO @ 15:08:59]   Platform system: Linux-5.19.0-38-generic-x86_64-with-debian-bookworm-sid
[codecarbon INFO @ 15:08:59]   Python version: 3.7.16
[codecarbon INFO @ 15:08:59]   Available RAM : 62.488 GB
[codecarbon INFO @ 15:08:59]   CPU count: 16
[codecarbon INFO @ 15:08:59]   CPU model: 11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
[codecarbon INFO @ 15:08:59]   GPU count: 1
[codecarbon INFO @ 15:08:59]   GPU model: 1 x NVIDIA GeForce RTX 3090
```

From this, I can say that the GPU is correctly recognized. Then, the recommender system starts, and among all the other parameters, there is:

`device = cuda`
Then it computes recommendation metrics, and CodeCarbon outputs:

```
17 Apr 15:09    INFO  best valid : OrderedDict([('recall@10', 0.083), ('mrr@10', 0.1832), ('ndcg@10', 0.0934), ('hit@10', 0.4634), ('precision@10', 0.0748)])
17 Apr 15:09    INFO  test result: OrderedDict([('recall@10', 0.085), ('mrr@10', 0.1979), ('ndcg@10', 0.1032), ('hit@10', 0.4719), ('precision@10', 0.0828)])
[codecarbon INFO @ 15:09:10] Energy consumed for RAM : 0.000048 kWh. RAM Power : 23.433099746704105 W
[codecarbon INFO @ 15:09:10] Energy consumed for all GPUs : 0.000000 kWh. All GPUs Power : 0.0 W
[codecarbon INFO @ 15:09:10] Energy consumed for all CPUs : 0.000051 kWh. All CPUs Power : 24.894763107709608 W
[codecarbon INFO @ 15:09:10] 0.000099 kWh of electricity used since the begining.
```

As you can see, the GPU energy consumed is 0, and the same holds for the power.
I'm sure the model has been trained on the GPU: launching `nvidia-smi` during the training shows the python process executing on the GPU, and I can recognize it from the PID. Here's the source code of the model (very very simple):

```
from recbole.quick_start import run_recbole
from codecarbon import EmissionsTracker


`tracker = EmissionsTracker()`
`tracker.start()`
`run_recbole(model='Pop', dataset='ml-100k')`
`tracker.stop()`
```

Any suggestion/idea?

**Comment by benoit-cty** [comment] 2023-04-19 20:25
It's surprising, what is your OS ?

**Comment by giuspillo** [comment] 2023-04-19 21:38
Currently, the OS is `Linux-5.19.0-38-generic-x86_64-with-debian-bookworm-sid`
as you can see from the line of codecarbon (if this should be useful).

I've changed the machine, so now I'm using another computer on which codecarbon works properly; in any case, it could be useful solving this issue also for other users.

Here is the output (`<empty>` means codecarbon did not output that value, while `<hidden>` means I've hidden those values for privacy reasons).

```
timestamp		2023-04-17T15:04:04
project_name		test_proj
run_id			10c42995-0492-406d-9935-1d9e9b2a4bae
duration		3.514338732
emissions		1.16E-05
emissions_rate		0.003311737
cpu_power		32.82109676
gpu_power		0
ram_power		23.43309975
cpu_energy		3.20E-05
gpu_energy		0
ram_energy		2.29E-05
energy_consumed		5.49E-05
country_name		Italy
country_ido_code	ITA
region			<hidden>
cloud_provider		<empty>
cloud_region		<empty>
os			Linux-5.19.0-38-generic-x86_64-with-debian-bookworm-sid
python_version		3.7.16
cpu_count		16
cpu_model		11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz
gpu_count		1
gpu_model		1 x NVIDIA GeForce RTX 3090
longitude		<hidden>
latitude		<hidden>
ram_total_size		62.48826599
tracking_mode		machine
on_cloud		N
```

**Comment by EnJunChoong** [comment] 2023-04-24 13:18
Facing similar issue here: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/C84289~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/C84289~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



timestamp | 2023-04-24T16:16:01 | 2023-04-24T17:21:52
-- | -- | --
project_name | codecarbon | codecarbon
run_id | aba0c1c5-e69b-4c6d-bc46-d4580421e221 | b4d6ffcb-3c25-46bf-954d-20230490a9b4
duration | 543.8636763 | 3926.980908
emissions | 0.005524847 | 0.039892176
emissions_rate | 0.010158515 | 0.010158485
cpu_power | 42.5 | 42.5
gpu_power | 0 | 0
ram_power | 23.59234571 | 23.59234571
cpu_energy | 0.006420527 | 0.046359596
gpu_energy | 0 | 0
ram_energy | 0.00356171 | 0.025717172
energy_consumed | 0.009982237 | 0.072076768
country_name | Indonesia | Indonesia
country_iso_code | IDN | IDN
region | --hidden-- | --hidden--
cloud_provider |   |  
cloud_region |   |  
os | Linux-4.15.0-169-generic-x86_64-with-glibc2.2.5 | Linux-4.15.0-169-generic-x86_64-with-glibc2.2.5
python_version | 3.8.16 | 3.8.16
cpu_count | 8 | 8
cpu_model | Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz | Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
gpu_count | 1 | 1
gpu_model | 1 x NVIDIA A100-PCIE-40GB | 1 x NVIDIA A100-PCIE-40GB
longitude | --hidden-- | --hidden--
latitude | --hidden-- | --hidden--
ram_total_size | 62.91292191 | 62.91292191
tracking_mode | machine | machine
on_cloud | N | N



</body>

</html>

**Comment by benoit-cty** [comment] 2023-04-25 08:59
Who, great, thanks for investigating. 

Do you know how we could handle this in dependencies ?

**Comment by EnJunChoong** [comment] 2023-04-28 02:32
hi Benoit, 

We can programmatically get local nvcc version prior to installing pynvml package, but this might not be so straightforward across different machine OS, etc. 

I suggest we provide a more intuitive warning when an Exception is capture in codecarbon.core.gpu.get_gpu_details. Instead of debug level, we can log a warning that would be visible when user uses the default log level. 

Warning message can be along the line of "Failed to get gpucompute processes. Python package pynvml installed is <version>. Please cross check version is compatible with installed nvcc version"

**Comment by yang0369** [comment] 2023-07-14 02:37
![image](https://github.com/mlco2/codecarbon/assets/41265511/f18f997d-86b9-483f-8bdd-70a7db940b2b)
Dear Author, I got the similar error, where GPU model was identified but no consumption recorded when I was training model using GPU. 

I have also checked my cuda version, which is compatible with pynvml.
<img width="515" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/5fb3ef35-be40-4e80-a7bd-6b8e28059789">

Could you pls advise what could go wrong? Thanks

**Comment by benoit-cty** [comment] 2023-07-16 05:31
Hello,
Sorry to hear that, could you try these commands and give the outputs:
* In terminal:
  - `pip show pynvml`
  -  `nvidia-smi | grep CUDA`
* In Python:
  - ```
from codecarbon.core.gpu import get_gpu_details
get_gpu_details()
```
  - ```
import pynvml
pynvml.nvmlInit()
h = pynvml.nvmlDeviceGetHandleByIndex(0)
pynvml.nvmlDeviceGetPowerUsage(h)
```

**Comment by yang0369** [comment] 2023-07-17 03:04
Dear Author, Thank you for the prompt reply. Pls see my outputs below:
![image](https://github.com/mlco2/codecarbon/assets/41265511/c78fd8b8-9d5b-4a14-b865-0601fe707a22)

<img width="525" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/e8c7e1ae-b871-4c6f-9690-16139fb64563">

<img width="321" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/9a9188f6-e333-4eae-8d15-05afaf8aaabd">

**Comment by yang0369** [comment] 2023-07-17 05:03
<img width="841" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/1041fbdc-c3b6-4f1f-a910-b5008e63a839">
I have also checked the CPU consumption, seems it has no fluctuations at all

**Comment by benoit-cty** [comment] 2023-07-17 08:45
Thanks it is very strange that `pynvml.nvmlDeviceGetPowerUsage(h)` work but not [`get_gpu_details()`](https://github.com/mlco2/codecarbon/blob/f9b8506b91bdbde5b5384d8cd31cf7958a0e8cb9/codecarbon/core/gpu.py#L174) and without error !

Could try these in python interpreter:

```py
from codecarbon.core.gpu import *
import pynvml
pynvml.nvmlInit()
pynvml.nvmlDeviceGetCount()  # Expect more than 0 but maybe it's the problem
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
pynvml.nvmlDeviceGetPowerUsage(handle)
get_memory_info(handle)
get_gpu_name(handle)
get_uuid(handle)
get_temperature(handle)
get_power_usage(handle)
get_power_limit(handle)
get_gpu_utilization(handle)
get_compute_mode(handle)
get_compute_processes(handle)
get_graphics_processes(handle)
```

CPU is constant probably because CodeCabon can't access to your RAPL file, see https://github.com/mlco2/codecarbon/issues/244

**Comment by yang0369** [comment] 2023-07-17 13:55
<img width="507" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/c75a2033-dd72-4e42-bed9-038f591bfdc7">
seems the workaround for CPU tracker requires sudo right, I won't try it as I don't have admin for this machine. Thanks for the info though!

**Comment by benoit-cty** [comment] 2023-07-17 14:04
Thanks, so everything seems to work for the first GPU, but not when iterating over the 5 GPU,
Could you try:


```py
from codecarbon.core.gpu import *
import pynvml
pynvml.nvmlInit()

for i in range(pynvml.nvmlDeviceGetCount()):
    handle = pynvml.nvmlDeviceGetHandleByIndex(i)
    print(pynvml.nvmlDeviceGetPowerUsage(handle))
    print(get_gpu_name(handle))

```


For CPU I'm working on https://github.com/mlco2/codecarbon/pull/316 that will use the CPU load to estimate the power.

**Comment by yang0369** [comment] 2023-07-18 01:34
Thanks. I have tried to run the snippet in python script. and got this error:
<img width="895" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/5cbe51ea-b3d2-4a4c-b7c4-86cceb27078c">

The bit context here: I have 5 GPUs in this workstation, where 4 of them are computational, and 1 is graphics with no computing power. It seems the error was caused by the graphics GPU.

**Comment by yang0369** [comment] 2023-07-18 01:36
I am able to print for the 4 computational GPUs after I skipped the problematic grahpics GPU
<img width="444" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/d9c23db0-bcd7-4625-8ee8-5ce343adc15d">

<img width="965" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/661755a4-e2d0-4b65-a417-055a8c44acd5">

**Comment by benoit-cty** [comment] 2023-07-18 07:15
Thanks for this debugging, so the solution is to add a try/except to manage the GPU list.

**Comment by yang0369** [comment] 2023-07-19 05:50
> Thanks for this debugging, so the solution is to add a try/except to manage the GPU list.

Thank you!

**Comment by benoit-cty** [comment] 2023-07-19 06:45
You're welcome, can you test this branch : https://github.com/mlco2/codecarbon/pull/429 ?

**Comment by yang0369** [comment] 2023-07-20 03:56
I have just tested this branch #429 , it works like a charm! I have also validated that the consumption from codecarbon tallies with "nvidia-smi" output for GPUs.

<img width="1009" alt="image" src="https://github.com/mlco2/codecarbon/assets/41265511/77fd4db0-afb6-490a-a8f9-0d3cea31b921">

**Comment by benoit-cty** [comment] 2023-07-25 06:23
Closed by https://github.com/mlco2/codecarbon/pull/429

**Closed by benoit-cty** 2023-07-25 06:23 UTC
