### ISSUE TITLE
Some test needs root password during their execution

### ISSUE THREAD

**Issue by galbini** [mlco2/codecarbon#575] opened 2024-06-16 08:26 UTC
* CodeCarbon version: latest (git clone)
* Python version:  3.11
* Operating System: MacOs 14.2.1

### Description

Some test needs root password during their execution.
tests/test_config.py::TestConfig::test_full_hierarchy Password:
tests/test_custom_handler.py::TestCarbonCustomHandler::test_carbon_tracker_custom_handler
tests/test_custom_handler.py::TestCarbonCustomHandler::test_decorator_flush
tests/test_emissions_tracker_constant.py::TestCarbonTrackerConstant::test_carbon_tracker_offline_constant

I stopped at 50% of execution

### What I Did

```
hatch run test:package
```

**Comment by inimaz** [comment] 2024-06-17 15:09
Possible duplicate of #565

**Comment by inimaz** [comment] 2024-07-24 15:09
This has been resolved in master, tested in local to run the command and I don't have the issue now. Feel free to reopen if it still occurs

**Closed by inimaz** 2024-07-24 15:09 UTC
Labels: duplicate
