### ISSUE TITLE
codecarbon and memray interaction

### ISSUE THREAD

**Issue by lcrmorin** [mlco2/codecarbon#489] opened 2024-01-04 22:39 UTC
I was trying to use code carbon along memray magic. It seems that the %%memray_flamegraph magic create (and overide) something nommed tracker. That prevent further use of codecarbon tracker. I don't know if the problem is on code carbon side. But currently I could't add energy consumption in my tracker.

**Comment by inimaz** [comment] 2024-01-12 15:14
Hello @lcrmorin,
in order to be able to reproduce this issue, could you give us an snippet of how you are running memray and codecarbon together? Also the exact logs of the error you are seeing.
Thanks a lot!

**Comment by benoit-cty** [comment] 2024-01-15 09:37
If you use something like `tracker = EmissionsTracker(project_name="classification-measure")` you could try another name, like `codecarbon_tracker = EmissionsTracker(project_name="classification-measure")`.

Does it works ?

**Comment by lcrmorin** [comment] 2024-01-15 19:06
Seems like it would work. In the end I removed memray. As it is a profiler (and not a sampling profiler) it would fill the drive then crash with a bit of calculations.

**Comment by inimaz** [comment] 2024-01-15 22:58
Closing this. Looks like it is solved.

**Closed by inimaz** 2024-01-15 22:58 UTC
Labels: question
